	  CREATE MATERIALIZED VIEW analytics.total_inventory_transaction_view as select row_number() over(order by transaction_date) as transaction_id, *
from (
    select  REC_PLANT as source,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=PLANT) as source_type, STORAGE_LOCATION as destination,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=STORAGE_LOCATION) as destination_type,material,(SELECT MATERIAL_DESCRIPTION FROM master.material where material = MATERIAL_NAME) as material_description,  QUANTITY as quantity,'ISSUE' as transaction_type, STO as shipment_order, CUSTOMER_PO as customer_po, PRO_NUMBER as tracking_number, GOOD_ISSUE_DATE as transaction_date from validstage.PLANT_SAP_VALID_STAGE
    union
    select ISSUED_FROM as source,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=ISSUED_FROM) as source_type,RECEIVED_TO as destination,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=RECEIVED_TO) as destination_type,material,(SELECT MATERIAL_DESCRIPTION FROM master.material where material = MATERIAL_NAME) as material_description, ACTUAL_QUANTITY as quantity,'RECEIPT' as transaction_type,null as shipment_order,  CUSTOMER_PURCHASE_ORDER_NUMBER as customer_po, GE_FSG_TRACKING_NUMBER as tracking_number, RECEIPT_DATE as transaction_date from validstage.FSG_RECEIPT_VALID_STAGE
    union
    select ISSUED_FROM as source,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=ISSUED_FROM) as source_type,RECEIVED_TO as destination,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=RECEIVED_TO) as destination_type,material,(SELECT MATERIAL_DESCRIPTION FROM master.material where material = MATERIAL_NAME) as material_description, QUANTITY_SHIPPED as quantity, 'ISSUE' as transaction_type, null  as shipment_order,  CUSTOMER_PURCHASE_ORDER_NUMBER as customer_po, GE_FSG_TRACKING_NUMBER as tracking_number, ISSUED_DATE as transaction_date from validstage.FSG_ISSUED_VALID_STAGE
                union
                select storage_location as source,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=storage_location) as source_type,customer as destination,(SELECT LOC_TYPE from master.loc_type_mapping where loc_type_name=customer) as destination_type,material,(SELECT MATERIAL_DESCRIPTION FROM master.material where material = MATERIAL_NAME) as material_description,assetinstalled as quantity,'CONSUMED' as transaction_type,
                null  as shipment_order,null as customer_po, null as tracking_number,installation_date as transaction_date from analytics.analytics_installation 
) total_inventory_transaction_view 
order by transaction_date;